spring:
  application:
    name: microservice-discovery-eureka-ha
---
spring:
  config:
    activate:
      on-profile: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    instance-id: eureka-peer1-${random.value}
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
---
spring:
  config:
    activate:
      on-profile: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    instance-id: eureka-peer2-${random.value}
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
